### ISSUE TITLE
How to use SSH with qemu running within docker

### ISSUE THREAD

**Issue by ykoehler** [crops/poky-container#12]
Sorry if this doesn't belong here, but now since I can run qemu within the docker container, I tried to map the port 22 within to the host using -p 2222:22 and it didn't worked as expected, I guess that map to the docker container itself and not to the qemu instance running within, so, how would one access the qemu ssh from the host?

**Comment by rewitt1** [comment]
slirp is doing port forwarding as well, and by default it forwards 2222 to
22. So you would need to use

-p 2222:2222
