### ISSUE TITLE
Can not execute: bitbake -c menuconfig my-linux

### ISSUE THREAD

**Issue by thuyminhtran** [crops/poky-container#17]
Hi Markdown,
My envs is : YP2.4_M1, on host PC 14.04
docker run --rm -it -v /data:/workdir crops/poky:ubuntu-16.04 --workdir=/workdir
I got some issues as below:
> scripts/kconfig/lxdialog/menubox.o: In function `do_scroll':
> menubox.c:(.text+0x38): undefined reference to `wrefresh'
> scripts/kconfig/lxdialog/menubox.o: In function `do_print_item':
> menubox.c:(.text+0x17e): undefined reference to `wrefresh'
> scripts/kconfig/lxdialog/menubox.o: In function `print_buttons':
> menubox.c:(.text+0x2b8): undefined reference to `wrefresh'
> scripts/kconfig/lxdialog/menubox.o: In function `print_arrows.constprop.0':
> menubox.c:(.text+0x3c3): undefined reference to `wrefresh'
> collect2: error: ld returned 1 exit status
> scripts/Makefile.host:116: recipe for target 'scripts/kconfig/mconf' failed
> make[3]: *** [scripts/kconfig/mconf] Error 1

Regards,

**Comment by LuisMendoza94** [comment]
The reason is that the crop/poky image is missing the ncurses library to use it, you can do what is suggested in #19 and install the **libncurses5-dev** package.

**Comment by rewitt1** [comment]
Since there haven't been any other comments, I'm closing with the solution by @LuisMendoza94  being accepted.
