### ISSUE TITLE
How to add internal CA certificates to the container

### ISSUE THREAD

**Issue by mikevolzer** [crops/poky-container#31]
What is the best way to add an internal corporate CA to this image?

I would like to do this automatically so that it can be incorporated into our CI build.

Thanks!

**Comment by rewitt1** [comment]
Hi @mikevolzer,

You'd need to create a new Dockerfile that is derivative, or modify the current one, and then build your own image to be used with your CI.

If you need root access to do your configuration(which I really need to document), it would be similar to the fragment below:
```
FROM crops/poky

# Let's say the commands you use to add whatever configuration you need require root
USER root

RUN some-commands-to-configure-container

# This line is needed if you want the container to continue to automatically create users for you
# based on the workdir.
USER usersetup
```

**Comment by mikevolzer** [comment]
Hi @rewitt1 

Thank you so much for your help. This worked perfectly!
