### ISSUE TITLE
PATH environment variable can not be modified

### ISSUE THREAD

**Issue by benbrummer** [crops/poky-container#41]
I tried to add a directory to the PATH, but it is not possible in the poky containers. (Tried with crops/poky and poky:ubuntu-18.04).

### dockerfile
`FROM crops/poky

ENV SOME_PATH=/SOME/PATH
ENV PATH="$SOME_PATH:$PATH"

CMD bash`

### Result: PATH is not updated
`pokyuser@7eab69c2b7c5:~$ env
HOSTNAME=7eab69c2b7c5
SHELL=/bin/sh
TERM=xterm
USER=pokyuser
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SUDO_USER=usersetup
SUDO_UID=70
USERNAME=pokyuser
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
PWD=/home/pokyuser
LANG=en_US.UTF-8
SHLVL=2
SUDO_COMMAND=/usr/bin/poky-launch.sh /home/pokyuser /bin/sh -c bash
HOME=/home/pokyuser
SOME_PATH=/SOME/PATH
LOGNAME=pokyuser
LESSOPEN=| /usr/bin/lesspipe %s
SUDO_GID=70
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
`

**Comment by rewitt1** [comment]
This is due to "secure_path" being set in the sudoers file. I've fixed this locally without using "exempt_group", but I'm waiting to push the change until I get a test that works on all distros that doesn't require building a test container.

**Comment by rewitt1** [comment]
Should be fixed with ad9c16f2c6c39ef24d019ebf19c1e89e14b24fe6.
