### ISSUE TITLE
runqemu and devtool inside poky-container

### ISSUE THREAD

**Issue by dagomez137** [crops/poky-container#42]
Hi!

I'm trying to use `devtool` inside the container which is already running the qemu image. Would this be possible?

```sh
docker run --rm -it -p 2222:2222 -v $PWD:/workdir crops/poky:debian-9 --workdir=/workdir
source poky/oe-init-build-env
MACHINE=qemux86-64 core-image-minimal
runqemu qemux86-64 slirp nographic
```

Now, how can I connect a new container to use `devtool` in there and send the devtool results to the running image?

Thanks in advance!

**Comment by rewitt1** [comment]
Hi @dagmcr,

Does it need to be a separate container? For instance the below works for me when using core-image-sato:

### Inside container
```% runqemu slirp```

### In another shell on host
```
% docker exec --user=pokyuser -it CONTAINERID bash
pokyuser@bdae98f98ef7:/home/yoctouser$ ssh -l root -p 2222 localhost
root@qemux86:~#
```

This means that port 2222 is working for the ssh port. You should be able to do
```devtool deploy-target -s -P 2222 recipename root@localhost```
if you source *oe-init-build-env* in the second shell.

**Comment by dagomez137** [comment]
Hi @rewitt1,

Thanks for the help! That's exactly what I was looking for and it worked so well.
