### ISSUE TITLE
All Docker images are currently Ubuntu 18.04

### ISSUE THREAD

**Issue by ssfivy** [crops/poky-container#46]
## Analysis
Recent commit 7389f739a825ed14db499194f693eb5b6deb17fb changed the base image from ubuntu 16.04 to 18.04.

However, the sed command in build-and-test.sh here :
 https://github.com/crops/poky-container/blob/7389f739a825ed14db499194f693eb5b6deb17fb/build-and-test.sh#L21 

are still trying to pattern-match against 16.04. This results in all images in docker hub to become Ubuntu 18.04 images since the base image isn't updated to opensuse, fedora, etc.

.travis.yml probably also needs updating, if this previous commit is an indication: a7959cc9ff22d8ecdd1b5fb7af22d9c778348c4f

## How to reproduce:
1. Run any of these commands:

    a. `docker run -it crops/poky:fedora-30`
    b. `docker run -it crops/poky:opensuse-15.1`
    c. `docker run -it crops/poky:ubuntu-19.04`

2. Inside the container, run `cat /etc/os-release`

## Expected result:
Different information on different distros, and none of them saying ubuntu 18.04

## Got result:
On all distro tags:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by rewitt1** [comment]
Wow, thanks for this! I'm fixing it right now.

**Comment by rewitt1** [comment]
Hi @ssfivy,

This should be fixed with 531a5e82f087c7ee75e2aeff9ad32ac6cb2c9550.

**Comment by rewitt1** [comment]
I also added b5a1a2713fea92aaf36059f2bf3df3162ef034db to hopefully prevent this in the future.

**Comment by ssfivy** [comment]
Tested with the commands above, seems good to me now, thanks!
