### ISSUE TITLE
How To Mount An NFS Share Into A Container

### ISSUE THREAD

**Issue by peter197321** [crops/poky-container#52]
Hello All,

is it possible to mount a docker container (crops/poky) as an NFS share? So I can boot up a machine using a bootable image that is created by crops/poky?

**Comment by rewitt1** [comment]
Hi @peter197321,

It's should be possible to do a complete network boot using PXE(or whatever a platform uses) in combination with NFS. However, I'm not sure how crops/poky impacts that ability.

If you want to boot using an NFS share, it shouldn't matter whether you use crops/poky to build the rootfs, or if you use the actual host. As long as the directory containing the rootfs is visible to the NFS server, crops/poky shouldn't have any impact.

Let me know if I'm misunderstanding your question.

**Comment by peter197321** [comment]
You understood correctly :) Thanks a lot for suggestion. Yes, not need to attach docker container as NFS, it's OK actual host if rootfs visible.
