### ISSUE TITLE
apt-get install

### ISSUE THREAD

**Issue by peter197321** [crops/poky-container#55]
I need to install within the crops/poky container [some packages](https://www.nxp.com/docs/en/user-guide/IMX_YOCTO_PROJECT_USERS_GUIDE.pdf) (see in the linked document Chapter 3.1 Host packages) since I have no password - how to do it?

```
(base) PS C:\> docker run --rm -it -v myvolume:/workdir crops/poky --workdir=/workdir
pokyuser@06932ce45056:/workdir$ apt-get install curl
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
pokyuser@06932ce45056:/workdir$
```

**Comment by rewitt1** [comment]
Hi @peter197321,

I believe #19 answers your question. The summary being either:

1. Build the image yourself and install the packages. The special bit for doing this would be https://github.com/crops/poky-container/issues/19#issuecomment-343601187.
2. Use _docker exec_ as mentioned in https://github.com/crops/poky-container/issues/19#issuecomment-343571950. You could also drop to a shell using docker exec by instead doing ```docker exec -it -u root <image hash> bash```

**Comment by peter197321** [comment]
Hello,

per @rewitt1 it should be "**Build**" yourself, it means `crops/poky` are useless? So the intention is to reuse as much as possible from crops/poky.

Where and which parts should I modify to add my needed packages?

Thanks for your comments.

**Comment by moto-timo** [comment]
Closing this as we will not fix this. If you need a custom container image, please look into using [crops-generator](https://github.com/crops/crops-generator). See the [video](https://www.youtube.com/watch?v=JKolDAG_K4I). Take control of your own Open Source Adventure. Build your own container.
