### ISSUE TITLE
no license file

### ISSUE THREAD

**Issue by jamesdboone** [crops/poky-container#59]
Can you add a license file to indicate the license for this software?

Thanks!

**Comment by nmenon** [comment]
@rewitt1  I think the legal folks are looking for something like https://github.com/docker-library/hello-world/blob/master/LICENSE file in the source repo from where the final poky/crops container was built..

**Comment by rewitt1** [comment]
I just pushed https://github.com/crops/poky-container/commit/f43271cee7894ae6121db59bae17d144a4bfe70c.

When I have more time I'm planning on switching everything to SPDX as well.
