### ISSUE TITLE
"lz4c pzstd zstd" appear to be unavailable in PATH

### ISSUE THREAD

**Issue by robbie-cao** [crops/poky-container#67]
Hi, All,

```
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  lz4c pzstd zstd
```

There will be the above error when I build the most recent Yocto Project (up to https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=be665a79831c3dab7623e75d112bb35d72e39a82) following the steps in https://www.yoctoproject.org/docs/2.4.2/yocto-project-qs/yocto-project-qs.html#releases and https://www.yoctoproject.org/docs/2.4.2/dev-manual/dev-manual.html#setting-up-to-use-crops.

My steps as below:

```
# In host
$ mkdir work_dir && cd work_dir
$ git clone git://git.yoctoproject.org/poky
$ docker run --rm -it --net=host -v `pwd`:/home/pokyuser/yocto -w /home/pokyuser/yocto crops/poky

# In docker
$ source poky/oe-init-build-env
$ bitbake core-image-minimal
```

I notice that required tools lz4c pzstd zstd were added to HOSTTOOLS in change https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=1c51e6535bfead57c7913ae74d0d71af4dfe8195

Want to ask if there's plan to add these unavailable tools.

Thanks
Robbie Cao

**Comment by grahas** [comment]
Not helpful but I am having the same issue, did you find a work around?

**Comment by beroset** [comment]
You can install  `zstd` and `liblz4-tool` within your base container to make this work.  I encountered a similar problem with another container-based build and encountered this issue when searching for solutions.  So, for example, with an Ubuntu-based underlying image, you could add something like this to your Dockerfile.
```
RUN apt update && apt install -y zstd liblz4-tool
```

**Comment by grahas** [comment]
I ended up checking out the dunfell branch instead of the master to get it to work. I hadn’t realized it needed to be versioned back.

**Comment by moto-timo** [comment]
This should be resolved with:
https://github.com/crops/yocto-dockerfiles/commit/ac7b37bf2ee792d2f5ed2a17ebf2d5458abf48c9

Please pull the latest poky containers and test.
https://hub.docker.com/repository/docker/crops/poky#

**Comment by moto-timo** [comment]
Fixed in:
https://github.com/crops/yocto-dockerfiles/pull/57

**Comment by Real-Sunnoc** [comment]
sudo apt update && sudo apt install -y zstd liblz4-tool

**Comment by hongbo-miao** [comment]
For future people who come here, based on https://wiki.koansoftware.com/index.php/Upgrade_to_Yocto_honister_3.4
For "lz4c", might worth install `lz4` instead of `liblz4-tool` for new Ubuntu.

> The Yocto 3.4 release (fall 2021), also codenamed “Honister” introduces a couple of breaking changes, mostly related to the syntax. You can take a look at the official [migration guide](https://docs.yoctoproject.org/next/migration-guides/migration-3.4.html).
> 
> The following errors and fixes have appeared while attempting to update a meta-layer to the current release.
> 
> Error message:
> 
> > ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
>  lz4c pzstd zstd
> Explanation: The list of build-host prerequisites has changed, so you must install the missing packages, prefferably using the distribution’s package manager. In my case, I’m using Ubuntu 18.04 LTS.
> 
> Fix for Ubuntu Bionic or older:
> 
> > sudo apt-get install zstd liblz4-tool
>
> Fix for Ubuntu Focal or newer:
> 
> > sudo apt-get install zstd lz4
