### ISSUE TITLE
Publish image to ghcr.io

### ISSUE THREAD

**Issue by thielepaul** [crops/poky-container#70]
Can you please additionally publish the image to the github container registry?

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

This would be very useful as hub.docker.com has a rate limit off 100 / 6h for anonymous pulls.

**Comment by moto-timo** [comment]
I agree, but I am more or less single-handedly maintaining this project in my limited free time. The issue is to refactor our long-standing scripts for build-deploy to a more modern approach. We are open to contributions or an example fork that works. It is "On the list".

**Comment by pdlloyd** [comment]
What do you mean by a more modern approach? I'd be willing to help with this.

**Comment by pbrkr** [comment]
@pdlloyd After discussions at the Yocto summit & OEvDM last week, I'm going to take a look at this later this week. The plan is to replace the build scripts with the use of GitHub Actions such as https://github.com/docker/build-push-action as that keeps things lightweight and easy on development time. Container images will be pushed to ghcr.io as well as the Docker Hub if possible.

**Comment by moto-timo** [comment]
The dependent containers are now available, thanks to @pbrkr https://github.com/crops/yocto-dockerfiles/pull/89

**Comment by moto-timo** [comment]
Enabled with #98, #99, #100
