### ISSUE TITLE
Missing program: xxd

### ISSUE THREAD

**Issue by AI0867** [crops/poky-container#81]
For the `karo-nxp-bsp` fork of poky, the program `xxd` is needed for various recipes. I've had to copy this over from my host machine to get builds to work. It would be nice if this were included in the docker image.

**Comment by moto-timo** [comment]
We cannot add every single requirement for every single corner case. Some folks already complain we have too many things included. We also require that all distro/versions have the same experience, which can be a challenge with the older distros.

What we should probably do is document "How to create a derived `crops/poky` container".

**Comment by moto-timo** [comment]
Closing this as we will not fix this. If you need a custom container image, please look into using [crops-generator](https://github.com/crops/crops-generator). See the [video](https://www.youtube.com/watch?v=JKolDAG_K4I). Take control of your own Open Source Adventure. Build your own container.
