### ISSUE TITLE
Yocto-sumo build fails in container due to python 3.10

### ISSUE THREAD

**Issue by rlframe** [crops/poky-container#97]
I am attempting to build yocto-sumo in a container. This is a legacy version and it fails due to python 3.10 in /opt/poky/4.1/sysroots/x86_64-polysdk-linux/usr/bin. The following errors occur:
File "/home/jenkins/LEA/yocto/poky/bitbake/lib/bb/compat.py", line 3, in <module>
    from collections import MutableMapping, KeysView, ValuesView, ItemsView, OrderedDict
   ImportError: cannot import name 'MutableMapping' from 'collections' (/opt/poky/4.1/sysroots/x86_64-pokysdk-linux/usr/lib/python3.10     /collections/__init__.py)

This worked about a year ago with an older version of python in the sdk. Now in python 3.10 its collection.abc for the import. Is it possible to fix this or include an older version of python? I have the old sdk still installed, but not sure how to force the container to use it. Any help would be appreciated.
Thanks for your time,

**Comment by moto-timo** [comment]
sumo is very very long EOL (April 2019). You can go back in git history to an older time when poky-container still worked. We cannot support EOL releases and that was never a design goal.
